# Generated by Django 5.0.6 on 2024-11-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0003_cliente_fecha_registro_empleado_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='fecha_registro',
        ),
    ]
