# Generated by Django 5.0.6 on 2024-11-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0005_alter_empleado_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='estado_reserva',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado_venta',
        ),
    ]
