# Generated by Django 5.0.6 on 2024-11-17 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0007_detalleventa_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
