# Generated by Django 5.0.6 on 2024-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0008_servicios_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
