# Generated by Django 5.0.6 on 2024-09-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('numero_telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('estado_empleado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255)),
                ('descripcion_servicio', models.CharField(max_length=255)),
                ('categoria_servicio', models.CharField(max_length=255)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota_adicional', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado_turno', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_apertura', models.DateTimeField()),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recaudado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dni_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioXTurno',
            fields=[
                ('id_serv_x_tur', models.AutoField(primary_key=True, serialize=False)),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.servicio')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.turno')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoXTurno',
            fields=[
                ('id_emp_x_tur', models.AutoField(primary_key=True, serialize=False)),
                ('dni_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.empleado')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('hs_venta', models.TimeField()),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_venta', models.BooleanField()),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.caja')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=255)),
                ('monto_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota_adicional', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.cliente')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.turno')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.venta')),
            ],
        ),
    ]
