# Generated by Django 5.0.6 on 2024-09-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAS', '0002_rename_dni_emp_caja_empleado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Servicios',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='categoria_servicio',
            new_name='categoria_del_servicio',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='descripcion_servicio',
            new_name='descripcion_del_servicio',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='nombre_servicio',
            new_name='nombre_del_servicio',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='precio_servicio',
            new_name='precio_del_servicio',
        ),
    ]
