# Generated by Django 5.0.6 on 2024-09-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAS', '0003_rename_servicio_servicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
