# Generated by Django 5.0.6 on 2024-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_empleado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.CharField(max_length=255),
        ),
    ]
