# Generated by Django 5.0.6 on 2024-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='estado_reserva',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('cancelada', 'Cancelada')], default='en_proceso', max_length=20),
        ),
    ]
