# Generated by Django 5.0.6 on 2024-11-17 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='senia',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo dígitos.', regex='^[0-9]+$')]),
        ),
    ]
