# Generated by Django 5.0.6 on 2024-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0002_reservas_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='estado_reserva',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('En Proceso', 'En Proceso'), ('Cancelada', 'Cancelada')], default='en_proceso', max_length=20),
        ),
    ]
