# Generated by Django 5.0.6 on 2024-11-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0002_alter_empleado_estado_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='diseño_uñas',
            field=models.ImageField(blank=True, null=True, upload_to='diseño_uñas/'),
        ),
    ]
