# Generated by Django 5.0.6 on 2024-11-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0007_remove_servicios_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_registro',
        ),
    ]
