# Generated by Django 5.0.6 on 2024-11-24 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0009_remove_detalleventa_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten dígitos.', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='estado_reserva',
            field=models.CharField(choices=[('completada', 'Completada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='En Proceso', max_length=20),
        ),
    ]
