# Generated by Django 5.0.6 on 2024-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnaSol', '0010_alter_empleado_dni_alter_empleado_numero_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contraseña_original',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
